### ISSUE TITLE
missing swift support

### ISSUE THREAD

**Issue by foadsaliba** [brightcove/brightcove-player-sdk-ios-fw#1]
Hi,

I've been trying to implement the Brightcove iOS SDK and the FW extension using swift but found that the current examples can't be translated to Swift code. 

The two things I've run into so far are that 
* `BCOVFWSessionProviderAdContextPolicy` typedef isn't carried over to the swift wrapper for some reason. 
* `createFWPlaybackControllerWithAdContextPolicy:viewStrategy:` initializers aren't carried over to the swift wrappers either. 

Is there another way to implement the FW support in Swift or is the support just missing but not documented anywhere? 

Thanks,
Foad

**Comment by sjbushell** [comment]
Hi Foad,

Those specific items are derived from FreeWheel's FWContext protocol (a forward definition in our headers), so you have to make sure you add the AdManager include to your bridging header or they'll end up missing (without any really meaningful message from Xcode).

I could reproduce your problem easily by putting the Brightcove modules in the bridging header, but leaving out the AdManager.

So, must make sure you bringing header has something like this:

```
#import <Foundation/Foundation.h>
#import <AdManager/FWSDK.h>
#import <BrightcovePlayerSDK/BrightcovePlayerSDK.h>
#import <BrightcoveFW/BrightcoveFW.h>
```

Steve
